const CharacterDeta = [{
    id: 1,
    name: '阿笠麗',
    faceImage: '',
    bigImage: '',
    alt: '',
    mangaTitle: '',
    role: '当主',
    age: '',
    dialogue: '',
    past: '',
    story: '',
    characterComment1: '',
    characterComment2: '',
    characterComment3: '',
    characterComment4: ''
}
,{
    id: 2,
    name: '土井旭',
    faceImage: '',
    bigImage: '',
    alt: '',
    mangaTitle: '',
    role: '浪人',
    age: '',
    dialogue: '',
    past: '',
    story: '',
    characterComment1: '',
    characterComment2: '',
    characterComment3: '',
    characterComment4: ''
},
{
    id: 3,
    name: '',
    faceImage: '',
    bigImage: '',
    alt: '',
    mangaTitle: '',
    role: '',
    age: '',
    dialogue: '',
    past: '',
    story: '',
    characterComment1: '',
    characterComment2: '',
    characterComment3: '',
    characterComment4: ''
}]